// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	sqlwrap "github.com/kornharem08/gorm"
	mock "github.com/stretchr/testify/mock"
)

// ISQLConnect is an autogenerated mock type for the ISQLConnect type
type ISQLConnect struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *ISQLConnect) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Database provides a mock function with no fields
func (_m *ISQLConnect) Database() sqlwrap.IDatabase {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Database")
	}

	var r0 sqlwrap.IDatabase
	if rf, ok := ret.Get(0).(func() sqlwrap.IDatabase); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sqlwrap.IDatabase)
		}
	}

	return r0
}

// NewSession provides a mock function with no fields
func (_m *ISQLConnect) NewSession() (sqlwrap.ISQLSession, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewSession")
	}

	var r0 sqlwrap.ISQLSession
	var r1 error
	if rf, ok := ret.Get(0).(func() (sqlwrap.ISQLSession, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() sqlwrap.ISQLSession); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sqlwrap.ISQLSession)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewISQLConnect creates a new instance of ISQLConnect. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISQLConnect(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISQLConnect {
	mock := &ISQLConnect{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
