// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ISQLSession is an autogenerated mock type for the ISQLSession type
type ISQLSession struct {
	mock.Mock
}

// Commit provides a mock function with no fields
func (_m *ISQLSession) Commit() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, value
func (_m *ISQLSession) Create(ctx context.Context, value interface{}) error {
	ret := _m.Called(ctx, value)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, conds
func (_m *ISQLSession) Delete(ctx context.Context, conds ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, conds...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) error); ok {
		r0 = rf(ctx, conds...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: ctx, result, conds
func (_m *ISQLSession) Find(ctx context.Context, result interface{}, conds ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, result)
	_ca = append(_ca, conds...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, ...interface{}) error); ok {
		r0 = rf(ctx, result, conds...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// First provides a mock function with given fields: ctx, result, conds
func (_m *ISQLSession) First(ctx context.Context, result interface{}, conds ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, result)
	_ca = append(_ca, conds...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for First")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, ...interface{}) error); ok {
		r0 = rf(ctx, result, conds...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Rollback provides a mock function with no fields
func (_m *ISQLSession) Rollback() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, column, value
func (_m *ISQLSession) Update(ctx context.Context, column string, value interface{}) error {
	ret := _m.Called(ctx, column, value)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, column, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewISQLSession creates a new instance of ISQLSession. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISQLSession(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISQLSession {
	mock := &ISQLSession{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
